# Generated by Django 3.0 on 2020-03-04 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20200304_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='last_updated_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 4, 19, 59, 59, 354338)),
        ),
    ]
