# Generated by Django 3.0 on 2020-03-04 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20200304_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 3, 4, 20, 3, 37, 291453)),
        ),
        migrations.AlterField(
            model_name='note',
            name='last_updated_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 4, 20, 3, 37, 291453)),
        ),
    ]
