# Generated by Django 3.0 on 2020-03-04 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20200304_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='last_updated_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 4, 20, 4, 58, 556637)),
        ),
    ]
