# Generated by Django 3.0 on 2020-03-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_auto_20200304_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='last_updated_date',
            field=models.DateField(),
        ),
    ]
