# Generated by Django 3.0 on 2020-03-04 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_auto_20200304_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='note',
            name='last_updated_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
