# Generated by Django 3.0 on 2020-03-04 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_auto_20200304_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='last_updated_date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
