# Generated by Django 3.0 on 2020-03-04 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0015_auto_20200304_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='created_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
