# Generated by Django 3.0 on 2020-03-04 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0016_note_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created_date',
            field=models.DateField(verbose_name=datetime.date.today),
        ),
    ]
