# Generated by Django 3.0 on 2020-03-04 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0017_auto_20200304_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='note',
            name='last_updated_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Updated Date'),
        ),
    ]
